import os

BROKER_VHOST = os.getenv("BROKER_VHOST")
BROKER_URL = os.getenv("BROKER_URL")

RABBITMQ_DEFAULT_USER = os.getenv("RABBITMQ_DEFAULT_USER")
RABBITMQ_DEFAULT_PASS = os.getenv("RABBITMQ_DEFAULT_PASS")


